version: '3.4'

services:
  avitostart:
    image: avitostart
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    restart: always
    image: postgres:latest
    # volumes:
    # - ./.database/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=qwerty
      # - PG_DATA=/var/lib/postgresql/data/smth/
    ports:
      - 5436:5432

